name: VPS By HenDeveloper

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Enable and Start Tailscale
        run: |
          sudo systemctl enable tailscaled
          sudo systemctl start tailscaled

      - name: Authenticate with Tailscale
        run: |
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }}
          echo "Tailscale IP: $(sudo tailscale ip)" > tailscale_ip.txt
          cat tailscale_ip.txt

      - name: Backup sshd_config
        run: |
          sudo cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak

      - name: Configure SSH for Root Login and Password Authentication
        run: |
          sudo sed -i '/^#*PermitRootLogin/s/^#*PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo sed -i '/^#*PasswordAuthentication/s/^#*PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo sshd -t
          if [ $? -eq 0 ]; then
            echo "SSHD configuration valid. Attempting to restart..."
            sudo /usr/sbin/sshd -D &
          else
            echo "SSHD configuration invalid. Exiting."
            exit 1
          fi

      - name: Set Root Password
        run: |
          echo "root:HenFreetrial" | sudo chpasswd

      - name: Display Login Information
        run: |
          echo "================================="
          echo "Login Information:"
          echo "Username: root"
          echo "Password: HenFreetrial"
          echo "Tailscale IP: $(sudo tailscale ip)"
          echo "================================="
